name: shared
description: "-"
version: 0.0.0
publish_to: none

environment:
    sdk: ">=2.19.0-43.0.dev <3.0.0"

dependencies:
    http: ^0.13.4

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
