name: yukino_app
description: Yukino
version: 1.0.13-beta.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    animations: ^2.0.1
    archive: ^3.1.5
    better_player: ^0.0.79
    clipboard: ^0.1.3
    collection: ^1.15.0
    crypto: ^3.0.1
    dart_vlc: ^0.1.8
    encrypt: ^5.0.0
    extensions:
        path: packages/extensions
    flutter:
        sdk: flutter
    flutter_markdown: ^0.6.6
    fuzzy: ^0.4.0-nullsafety.0
    hetu_script: ^0.1.2+5
    html: ^0.15.0
    http: ^0.13.3
    json_annotation: ^4.4.0
    objectbox: ^1.2.0
    objectbox_flutter_libs: any
    ota_update: ^3.1.1
    package_info_plus: ^1.0.5
    path: ^1.8.0
    path_provider: ^2.0.2
    protocol_registry:
        git:
            url: https://github.com/zyrouge/dart_protocol_registry.git
            ref: 885fc4bdaf6a60e5fd27013b876a9d6bec3addc2
    shelf: ^1.2.0
    tar: ^0.5.1
    uni_links: ^0.5.1
    url_launcher: ^6.0.9
    utilx:
        git:
            url: https://github.com/yukino-app/yukino.git
            path: packages/utilx
    version: ^2.0.0
    wakelock: ^0.5.6
    window_manager:
        git:
            url: https://github.com/leanflutter/window_manager.git
            ref: a051716c04a05e41b0415ea43ba8dafa297e0d5b

dependency_overrides:
    utilx:
        path: packages/utilx

dev_dependencies:
    build_runner: ^2.0.5
    json_serializable: ^6.1.1
    lint: ^1.5.3
    objectbox_generator: any

flutter:
    uses-material-design: true
    assets:
        - assets/data/
        - assets/images/
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Italic.ttf
                style: italic
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 800
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
