name: kazahana
description: An extension-based Anime and Manga client.
publish_to: none
version: 3.0.0

environment:
    sdk: ">=2.18.0-272.0.dev <3.0.0"

dependencies:
    anilist:
        path: packages/anilist
    animations: ^2.0.3
    collection: ^1.16.0
    encrypt: ^5.0.1
    flutter:
        sdk: flutter
    json_annotation: ^4.6.0
    path: ^1.8.2
    path_provider: ^2.0.11
    perks: ^1.0.0
    provider: ^6.0.3
    shared:
        path: packages/shared
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    tenka_runtime:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka_runtime
    uni_links: ^0.5.1
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx

dev_dependencies:
    build_runner: ^2.0.0
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
    image: ^3.2.0
    json_serializable: ^6.3.1

flutter:
    uses-material-design: true
    fonts:
        - family: Inter
          fonts:
              - asset: ./assets/fonts/Inter-Regular.ttf
              - asset: ./assets/fonts/Inter-Medium.ttf
                weight: 600
              - asset: ./assets/fonts/Inter-Bold.ttf
                weight: 800
        - family: GreatVibes
          fonts:
              - asset: ./assets/fonts/GreatVibes-Regular.ttf
