name: Android (Apk)

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                  java-version: 12.x

            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm

            - uses: subosito/flutter-action@v1.5.3
              with:
                  channel: master

            - name: ğŸš§ Do prerequisites
              run: |
                  flutter pub get
                  npm ci
                  npm run generator:run

            - name: ğŸš© Check for existing releases
              run: npm run actions:check-release -- '-android.apk'

            - name: ğŸ”¨ Generate certificate
              run: |
                  mkdir -p ./certs/android
                  echo $KEY_FILE | base64 -di > ./certs/android/key.jks
              env:
                  KEY_FILE: ${{ secrets.ANDROID_CERT_FILE }}

            - name: ğŸ”¨ Building apk
              run: npm run android:build
              env:
                  KEY_PASSWORD: ${{ secrets.ANDROID_CERT_PASSWORD }}

            - name: ğŸ”¢ Get version
              uses: actions/github-script@v4
              id: app_version
              with:
                  result-encoding: string
                  script: |
                      const spawn = require("cross-spawn");
                      const result = spawn.sync("npm", ["run", "version:print", "-s"]);
                      if (result.status != 0) {
                        throw new Error(result.stderr.toString());
                      }

                      return result.stdout.toString().trim();

            - name: ğŸ“ Get files
              uses: actions/github-script@v4
              id: app_files
              with:
                  result-encoding: string
                  script: |
                      const fg = require("fast-glob");
                      return fg.sync("build/packed/android/*-android.apk").join("\n");

            - name: ğŸš€ Release apk
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.app_version.outputs.result }}
                  files: ${{ steps.app_files.outputs.result }}
                  draft: true
