name: Changelogs

on:
    workflow_dispatch:
    release:
        types:
            - published

jobs:
    changelogs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm

            - name: ğŸš§ Do prerequisites
              run: |
                  npm ci

            - name: ğŸ—ï¸ Update changes
              run: npm run actions:update-changelogs
              env:
                  DISCORD_RELEASE_HOOK: ${{ secrets.DISCORD_RELEASE_HOOK }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: ğŸ”¢ Get version
              uses: actions/github-script@v4
              id: app_version
              with:
                  result-encoding: string
                  script: |
                      const spawn = require("cross-spawn");
                      const result = spawn.sync("npm", ["run", "version:print", "-s"]);
                      if (result.status != 0) {
                        throw new Error(result.stderr.toString());
                      }

                      return result.stdout.toString().trim();

            - name: ğŸ—ï¸ Upload changelogs
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.app_version.outputs.result }}
                  files: cli/.cache/changelogs.json
                  draft: false
