name: MacOS (Dmg)

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: npm

            - uses: subosito/flutter-action@v1.5.3
              with:
                  channel: beta

            - name: ðŸš§ Do prerequisites
              run: |
                  flutter config --enable-macos-desktop
                  flutter pub get
                  npm ci
                  npm run hive:generate

            - name: ðŸ”¨ Building binaries
              run: npm run linux:macos

            - name: ðŸ“¦ Packing as dmg
              run: npm run linux:macos:dmg

            - name: ðŸš€ Upload dmg
              uses: actions/upload-artifact@v2
              with:
                  name: linux-appimage
                  path: build/packed/macos/*.dmg
